import type { DocumentType } from './types';
type Copy = { heading: string; empty: string; open: string; download: string; sent: string; loading: string; error: string; retry: string; types: Record<DocumentType, string> };
const copies: Record<string, Copy> = {
  de: { heading: 'Dokumente', empty: 'Hier erscheinen die Dokumente zu Ihrer Anfrage.', open: 'Öffnen', download: 'Herunterladen', sent: 'Ein Dokument ist in Ihrem Kundenportal verfügbar', loading: 'Dokumente werden geladen…', error: 'Dokumente konnten nicht geladen werden.', retry: 'Erneut versuchen', types: { INVOICE: 'Rechnung', CONTRACT: 'Vertrag', ACT: 'Leistungsnachweis', OTHER: 'Sonstiges Dokument' } },
  en: { heading: 'Documents', empty: 'Documents for your request will appear here.', open: 'Open', download: 'Download', sent: 'A document is available in your customer portal', loading: 'Loading documents…', error: 'Unable to load documents.', retry: 'Try again', types: { INVOICE: 'Invoice', CONTRACT: 'Contract', ACT: 'Service completion record', OTHER: 'Other document' } },
  ru: { heading: 'Документы', empty: 'Здесь появятся документы по вашей заявке.', open: 'Открыть', download: 'Скачать', sent: 'В вашем кабинете доступен документ', loading: 'Загрузка документов…', error: 'Не удалось загрузить документы.', retry: 'Повторить', types: { INVOICE: 'Счёт', CONTRACT: 'Договор', ACT: 'Акт выполненных работ', OTHER: 'Другой документ' } },
  tr: { heading: 'Belgeler', empty: 'Talebinizle ilgili belgeler burada görünecek.', open: 'Aç', download: 'İndir', sent: 'Müşteri portalınızda bir belge mevcut', loading: 'Belgeler yükleniyor…', error: 'Belgeler yüklenemedi.', retry: 'Tekrar dene', types: { INVOICE: 'Fatura', CONTRACT: 'Sözleşme', ACT: 'İş tamamlama tutanağı', OTHER: 'Diğer belge' } },
  pl: { heading: 'Dokumenty', empty: 'Tutaj pojawią się dokumenty dotyczące zgłoszenia.', open: 'Otwórz', download: 'Pobierz', sent: 'W panelu klienta dostępny jest dokument', loading: 'Ładowanie dokumentów…', error: 'Nie udało się wczytać dokumentów.', retry: 'Spróbuj ponownie', types: { INVOICE: 'Faktura', CONTRACT: 'Umowa', ACT: 'Protokół wykonania prac', OTHER: 'Inny dokument' } },
  ar: { heading: 'المستندات', empty: 'ستظهر هنا المستندات المتعلقة بطلبك.', open: 'فتح', download: 'تنزيل', sent: 'يتوفر مستند في بوابة العميل الخاصة بك', loading: 'جارٍ تحميل المستندات…', error: 'تعذر تحميل المستندات.', retry: 'إعادة المحاولة', types: { INVOICE: 'فاتورة', CONTRACT: 'عقد', ACT: 'محضر إنجاز الأعمال', OTHER: 'مستند آخر' } },
};
export function getDocumentCopy(locale?: string | null) { return copies[locale || 'de'] || copies.de; }
