const de = {
  title: 'Wie möchten Sie fortfahren?',
  previous: 'In diesem Browser wurde bereits eine Anfrage gesendet.',
  openPrevious: 'Bisherige Anfrage öffnen', newRequest: 'Neue Anfrage erstellen',
  previousHelp: 'Öffnet die Statusseite in einem neuen Tab. Dieses Formular bleibt geöffnet.',
  intro: 'Bestätigen Sie Ihre E-Mail-Adresse für eine weitere Anfrage. Ein Kundenkonto ist nicht erforderlich.',
  email: 'E-Mail-Adresse', send: 'Code senden', resend: 'Code erneut senden',
  sent: 'Wir haben einen Code an {email} gesendet. Geben Sie ihn hier ein. Er gilt 15 Minuten.',
  spam: 'Keine E-Mail erhalten? Prüfen Sie auch Ihren Spam-Ordner.',
  code: '6-stelliger Code', verify: 'E-Mail bestätigen', verified: 'E-Mail bestätigt. Sie können Ihre neue Anfrage jetzt senden.',
  invalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
  invalidCode: 'Der Code ist falsch, abgelaufen oder bereits verwendet. Prüfen Sie ihn oder fordern Sie einen neuen an.',
  deliveryError: 'Die E-Mail konnte nicht gesendet werden. Ihre Eingaben bleiben erhalten. Bitte versuchen Sie es erneut.',
  retry: 'Bitte warten Sie {seconds} Sekunden, bevor Sie es erneut versuchen.',
  checkError: 'Die Prüfung ist gerade nicht verfügbar. Ihre Eingaben bleiben erhalten. Bitte versuchen Sie es erneut.',
  pending: 'Bitte bestätigen Sie oben Ihre E-Mail-Adresse.',
  subject: 'PixelRing: Code für Ihre neue Anfrage',
  emailIntro: 'Mit diesem Code bestätigen Sie Ihre E-Mail-Adresse für eine neue Serviceanfrage. Es wird kein Kundenkonto erstellt.',
  expires: 'Gültig bis', ignore: 'Wenn Sie diesen Code nicht angefordert haben, ignorieren Sie diese E-Mail.',
};
type Copy = typeof de;
const copies: Record<string, Copy> = {
  de,
  en: {
    title: 'How would you like to continue?', previous: 'A request has already been sent from this browser.',
    openPrevious: 'Open previous request', newRequest: 'Create a new request', previousHelp: 'Opens the status page in a new tab. This form stays open.',
    intro: 'Confirm your email address to send another request. No customer account is required.',
    email: 'Email address', send: 'Send code', resend: 'Send a new code',
    sent: 'We sent a code to {email}. Enter it here. It is valid for 15 minutes.', spam: 'No email? Check your spam folder too.',
    code: '6-digit code', verify: 'Confirm email', verified: 'Email confirmed. You can now send your new request.',
    invalidEmail: 'Please enter a valid email address.', invalidCode: 'The code is incorrect, expired or already used. Check it or request a new one.',
    deliveryError: 'We could not send the email. Your form is preserved. Please try again.',
    retry: 'Please wait {seconds} seconds before trying again.', checkError: 'Verification is temporarily unavailable. Your form is preserved. Please try again.',
    pending: 'Please confirm your email address above.', subject: 'PixelRing: code for your new request',
    emailIntro: 'Use this code to confirm your email address for a new service request. No customer account will be created.',
    expires: 'Valid until', ignore: 'If you did not request this code, ignore this email.',
  },
  ru: {
    title: 'Что вы хотите сделать?', previous: 'Из этого браузера уже отправляли заявку.',
    openPrevious: 'Открыть предыдущую заявку', newRequest: 'Создать новую заявку', previousHelp: 'Страница статуса откроется в новой вкладке. Эта форма останется открытой.',
    intro: 'Подтвердите почту, чтобы отправить ещё одну заявку. Создавать личный кабинет не нужно.',
    email: 'Электронная почта', send: 'Получить код', resend: 'Отправить код ещё раз',
    sent: 'Мы отправили код на {email}. Введите его здесь. Код действует 15 минут.', spam: 'Нет письма? Проверьте также папку «Спам».',
    code: 'Код из 6 цифр', verify: 'Подтвердить почту', verified: 'Почта подтверждена. Теперь можно отправить новую заявку.',
    invalidEmail: 'Укажите корректный адрес почты.', invalidCode: 'Код неверный, просрочен или уже использован. Проверьте его или запросите новый.',
    deliveryError: 'Не удалось отправить письмо. Данные формы сохранены. Попробуйте ещё раз.',
    retry: 'Повторите попытку через {seconds} сек.', checkError: 'Проверка временно недоступна. Данные формы сохранены. Попробуйте ещё раз.',
    pending: 'Сначала подтвердите почту выше.', subject: 'PixelRing: код для новой заявки',
    emailIntro: 'Этот код подтверждает вашу почту для отправки новой заявки на обслуживание. Личный кабинет создан не будет.',
    expires: 'Действует до', ignore: 'Если вы не запрашивали код, проигнорируйте это письмо.',
  },
  tr: {
    title: 'Nasıl devam etmek istersiniz?', previous: 'Bu tarayıcıdan daha önce bir talep gönderildi.',
    openPrevious: 'Önceki talebi aç', newRequest: 'Yeni talep oluştur', previousHelp: 'Durum sayfası yeni sekmede açılır. Bu form açık kalır.',
    intro: 'Başka bir talep göndermek için e-postanızı doğrulayın. Müşteri hesabı gerekmez.',
    email: 'E-posta adresi', send: 'Kod gönder', resend: 'Yeniden kod gönder',
    sent: '{email} adresine bir kod gönderdik. Buraya girin. Kod 15 dakika geçerlidir.', spam: 'E-posta gelmedi mi? Spam klasörünü de kontrol edin.',
    code: '6 haneli kod', verify: 'E-postayı doğrula', verified: 'E-posta doğrulandı. Yeni talebinizi gönderebilirsiniz.',
    invalidEmail: 'Geçerli bir e-posta adresi girin.', invalidCode: 'Kod yanlış, süresi dolmuş veya kullanılmış. Kontrol edin ya da yeni kod isteyin.',
    deliveryError: 'E-posta gönderilemedi. Formunuz korunuyor. Lütfen tekrar deneyin.',
    retry: 'Tekrar denemeden önce {seconds} saniye bekleyin.', checkError: 'Doğrulama şu anda kullanılamıyor. Formunuz korunuyor. Tekrar deneyin.',
    pending: 'Önce yukarıda e-postanızı doğrulayın.', subject: 'PixelRing: yeni talebiniz için kod',
    emailIntro: 'Bu kod, yeni servis talebiniz için e-posta adresinizi doğrular. Müşteri hesabı oluşturulmaz.',
    expires: 'Son geçerlilik', ignore: 'Bu kodu siz istemediyseniz bu e-postayı yok sayın.',
  },
  pl: {
    title: 'Co chcesz zrobić?', previous: 'Z tej przeglądarki wysłano już zgłoszenie.',
    openPrevious: 'Otwórz poprzednie zgłoszenie', newRequest: 'Utwórz nowe zgłoszenie', previousHelp: 'Strona statusu otworzy się w nowej karcie. Formularz pozostanie otwarty.',
    intro: 'Potwierdź adres e-mail, aby wysłać kolejne zgłoszenie. Konto klienta nie jest wymagane.',
    email: 'Adres e-mail', send: 'Wyślij kod', resend: 'Wyślij kod ponownie',
    sent: 'Wysłaliśmy kod na {email}. Wpisz go tutaj. Jest ważny przez 15 minut.', spam: 'Brak wiadomości? Sprawdź również folder spam.',
    code: 'Kod 6-cyfrowy', verify: 'Potwierdź e-mail', verified: 'E-mail potwierdzony. Możesz wysłać nowe zgłoszenie.',
    invalidEmail: 'Podaj poprawny adres e-mail.', invalidCode: 'Kod jest błędny, wygasł lub został użyty. Sprawdź go lub poproś o nowy.',
    deliveryError: 'Nie udało się wysłać wiadomości. Dane formularza zostały zachowane. Spróbuj ponownie.',
    retry: 'Poczekaj {seconds} sekund przed kolejną próbą.', checkError: 'Weryfikacja jest chwilowo niedostępna. Dane formularza zachowano. Spróbuj ponownie.',
    pending: 'Najpierw potwierdź adres e-mail powyżej.', subject: 'PixelRing: kod do nowego zgłoszenia',
    emailIntro: 'Ten kod potwierdza adres e-mail dla nowego zgłoszenia serwisowego. Konto klienta nie zostanie utworzone.',
    expires: 'Ważny do', ignore: 'Jeśli nie proszono o ten kod, zignoruj tę wiadomość.',
  },
  ar: {
    title: 'كيف تريد المتابعة؟', previous: 'تم إرسال طلب سابقًا من هذا المتصفح.',
    openPrevious: 'فتح الطلب السابق', newRequest: 'إنشاء طلب جديد', previousHelp: 'تفتح صفحة الحالة في علامة تبويب جديدة ويبقى هذا النموذج مفتوحًا.',
    intro: 'أكد بريدك الإلكتروني لإرسال طلب آخر. لا يلزم إنشاء حساب عميل.',
    email: 'البريد الإلكتروني', send: 'إرسال الرمز', resend: 'إعادة إرسال الرمز',
    sent: 'أرسلنا رمزًا إلى {email}. أدخله هنا. الرمز صالح لمدة 15 دقيقة.', spam: 'لم تصلك الرسالة؟ تحقق أيضًا من مجلد الرسائل غير المرغوب فيها.',
    code: 'رمز من 6 أرقام', verify: 'تأكيد البريد', verified: 'تم تأكيد البريد. يمكنك الآن إرسال طلبك الجديد.',
    invalidEmail: 'أدخل عنوان بريد إلكتروني صالحًا.', invalidCode: 'الرمز غير صحيح أو منتهي الصلاحية أو مستخدم. تحقق منه أو اطلب رمزًا جديدًا.',
    deliveryError: 'تعذر إرسال البريد. تم الاحتفاظ ببيانات النموذج. حاول مرة أخرى.',
    retry: 'انتظر {seconds} ثانية قبل المحاولة مرة أخرى.', checkError: 'التحقق غير متاح مؤقتًا. تم الاحتفاظ ببيانات النموذج. حاول مرة أخرى.',
    pending: 'أكد بريدك الإلكتروني أعلاه أولًا.', subject: 'PixelRing: رمز لطلبك الجديد',
    emailIntro: 'يؤكد هذا الرمز بريدك الإلكتروني لإرسال طلب خدمة جديد. لن يتم إنشاء حساب عميل.',
    expires: 'صالح حتى', ignore: 'إذا لم تطلب هذا الرمز، فتجاهل هذه الرسالة.',
  },
};
export function getIntakeVerificationCopy(locale?: string | null): Copy {
  return copies[locale ?? 'de'] ?? de;
}
