const copy = {
  "de": {
    "actions": "Ihre Aufgaben",
    "notifications": "Neue Mitteilungen",
    "history": "Erledigte Aufgaben",
    "materials": "Dokumente und Fotoberichte",
    "latestRequests": "Letzte Anfragen",
    "emptyActions": "Aktuell ist nichts von Ihnen erforderlich.",
    "emptyNotifications": "Keine neuen Mitteilungen.",
    "emptyHistory": "Noch keine erledigten Aufgaben.",
    "emptyMaterials": "Noch keine Dokumente oder Fotoberichte.",
    "open": "Öffnen",
    "acknowledge": "Zur Kenntnis genommen",
    "markRead": "Als gelesen markieren",
    "reply": "Antworten",
    "upload": "Fotos hinzufügen",
    "submitted": "Übermittelt · wird geprüft",
    "completed": "Erledigt",
    "cancelled": "Zurückgenommen",
    "due": "Frist",
    "loading": "Wird geladen …",
    "error": "Aktualisierung fehlgeschlagen. Die zuletzt geladenen Informationen bleiben sichtbar.",
    "retry": "Erneut versuchen",
    "all": "Alle",
    "unread": "Ungelesen",
    "saved": "Gespeichert",
    "acknowledgeHint": "Die Bestätigung bedeutet nur Kenntnisnahme, keine Zahlung, Unterschrift oder Abnahme.",
    "status": "Status der Anfrage",
    "noAddress": "Adresse nicht angegeben",
    "request": "Anfrage",
    "account": "Bestätigtes Kundenkonto",
    "DOCUMENT": "Dokument",
    "REPORT": "Fotobericht",
    "REQUEST": "Ihre Rückmeldung",
    "MESSAGE": "Nachricht",
    "STATUS": "Status aktualisiert",
    "activeRequests": "Aktive Anfragen",
    "respondingTo": "Antwort auf",
    "cancelReply": "Antwort abbrechen",
    "responseSaved": "Antwort übermittelt",
    "responseLinkFailed": "Die Antwort wurde gespeichert, konnte aber noch nicht mit der Aufgabe verknüpft werden.",
    "retrySubmit": "Erneut zuordnen",
    "uploadRequired": "Bitte fügen Sie ein Foto hinzu.",
    "reviewStatus": "Wir prüfen Ihre Anfrage.",
    "progressStatus": "Wir bearbeiten Ihre Anfrage.",
    "holdStatus": "Die Anfrage ist vorübergehend pausiert.",
    "waitingStatus": "Wir warten auf Ihre Rückmeldung.",
    "closedStatus": "Die Anfrage wurde geschlossen.",
    "createdStatus": "Anfrage registriert",
    "noRequests": "Keine Anfragen in dieser Ansicht.",
    "viewResponse": "Antwort im Chat ansehen"
  },
  "en": {
    "actions": "Your actions",
    "notifications": "New notifications",
    "history": "Completed actions",
    "materials": "Documents and photo reports",
    "latestRequests": "Latest requests",
    "emptyActions": "Nothing is required from you at the moment.",
    "emptyNotifications": "No new notifications.",
    "emptyHistory": "No completed actions yet.",
    "emptyMaterials": "No documents or photo reports yet.",
    "open": "Open",
    "acknowledge": "I have read this",
    "markRead": "Mark as read",
    "reply": "Reply",
    "upload": "Add photos",
    "submitted": "Submitted · awaiting review",
    "completed": "Completed",
    "cancelled": "Withdrawn",
    "due": "Due",
    "loading": "Loading…",
    "error": "Could not refresh. Previously loaded information remains visible.",
    "retry": "Try again",
    "all": "All",
    "unread": "Unread",
    "saved": "Saved",
    "acknowledgeHint": "Acknowledgement confirms reading only, not payment, signature or acceptance of work.",
    "status": "Request status",
    "noAddress": "Address not provided",
    "request": "Request",
    "account": "Verified customer account",
    "DOCUMENT": "Document",
    "REPORT": "Photo report",
    "REQUEST": "Your response",
    "MESSAGE": "Message",
    "STATUS": "Status updated",
    "activeRequests": "Active requests",
    "respondingTo": "Responding to",
    "cancelReply": "Cancel reply",
    "responseSaved": "Response submitted",
    "responseLinkFailed": "Your response was saved but could not yet be linked to this action.",
    "retrySubmit": "Retry linking",
    "uploadRequired": "Please add a photo.",
    "reviewStatus": "We are reviewing your request.",
    "progressStatus": "We are working on your request.",
    "holdStatus": "The request is temporarily on hold.",
    "waitingStatus": "We are waiting for your response.",
    "closedStatus": "The request is closed.",
    "createdStatus": "Request registered",
    "noRequests": "No requests in this view.",
    "viewResponse": "View response in chat"
  },
  "ru": {
    "actions": "Ваши действия",
    "notifications": "Новые уведомления",
    "history": "Выполненные действия",
    "materials": "Документы и фотоотчёты",
    "latestRequests": "Последние заявки",
    "emptyActions": "Сейчас от вас ничего не требуется.",
    "emptyNotifications": "Новых уведомлений нет.",
    "emptyHistory": "Выполненных действий пока нет.",
    "emptyMaterials": "Документов и фотоотчётов пока нет.",
    "open": "Открыть",
    "acknowledge": "Ознакомился",
    "markRead": "Отметить прочитанным",
    "reply": "Ответить",
    "upload": "Добавить фото",
    "submitted": "Передано · ожидает проверки",
    "completed": "Выполнено",
    "cancelled": "Отозвано",
    "due": "Срок",
    "loading": "Загрузка…",
    "error": "Не удалось обновить данные. Показана последняя загруженная информация.",
    "retry": "Повторить",
    "all": "Все",
    "unread": "Непрочитанные",
    "saved": "Сохранено",
    "acknowledgeHint": "Подтверждение означает только ознакомление, а не оплату, подписание или приёмку работ.",
    "status": "Статус заявки",
    "noAddress": "Адрес не указан",
    "request": "Заявка",
    "account": "Подтверждённый аккаунт клиента",
    "DOCUMENT": "Документ",
    "REPORT": "Фотоотчёт",
    "REQUEST": "Ваш ответ",
    "MESSAGE": "Сообщение",
    "STATUS": "Статус обновлён",
    "activeRequests": "Активные заявки",
    "respondingTo": "Ответ на запрос",
    "cancelReply": "Отменить ответ",
    "responseSaved": "Ответ передан",
    "responseLinkFailed": "Ответ сохранён, но пока не удалось связать его с действием.",
    "retrySubmit": "Повторить привязку",
    "uploadRequired": "Прикрепите фотографию.",
    "reviewStatus": "Мы проверяем вашу заявку.",
    "progressStatus": "Мы работаем над вашей заявкой.",
    "holdStatus": "Работа по заявке временно приостановлена.",
    "waitingStatus": "Ожидаем ваш ответ.",
    "closedStatus": "Заявка закрыта.",
    "createdStatus": "Заявка зарегистрирована",
    "noRequests": "В этом списке пока нет заявок.",
    "viewResponse": "Посмотреть ответ в переписке"
  },
  "pl": {
    "actions": "Twoje zadania",
    "notifications": "Nowe powiadomienia",
    "history": "Ukończone zadania",
    "materials": "Dokumenty i fotorelacje",
    "latestRequests": "Ostatnie zgłoszenia",
    "emptyActions": "Obecnie nie musisz nic robić.",
    "emptyNotifications": "Brak nowych powiadomień.",
    "emptyHistory": "Brak ukończonych zadań.",
    "emptyMaterials": "Brak dokumentów i fotorelacji.",
    "open": "Otwórz",
    "acknowledge": "Zapoznałem się",
    "markRead": "Oznacz jako przeczytane",
    "reply": "Odpowiedz",
    "upload": "Dodaj zdjęcia",
    "submitted": "Przesłano · oczekuje na sprawdzenie",
    "completed": "Ukończono",
    "cancelled": "Wycofano",
    "due": "Termin",
    "loading": "Ładowanie…",
    "error": "Nie udało się odświeżyć. Wyświetlane są ostatnio pobrane dane.",
    "retry": "Spróbuj ponownie",
    "all": "Wszystkie",
    "unread": "Nieprzeczytane",
    "saved": "Zapisano",
    "acknowledgeHint": "Potwierdzenie oznacza tylko zapoznanie się, a nie płatność, podpis lub odbiór prac.",
    "status": "Status zgłoszenia",
    "noAddress": "Nie podano adresu",
    "request": "Zgłoszenie",
    "account": "Zweryfikowane konto klienta",
    "DOCUMENT": "Dokument",
    "REPORT": "Fotorelacja",
    "REQUEST": "Twoja odpowiedź",
    "MESSAGE": "Wiadomość",
    "STATUS": "Zaktualizowano status",
    "activeRequests": "Aktywne zgłoszenia",
    "respondingTo": "Odpowiedź na",
    "cancelReply": "Anuluj odpowiedź",
    "responseSaved": "Odpowiedź przesłana",
    "responseLinkFailed": "Odpowiedź zapisano, ale nie udało się powiązać jej z zadaniem.",
    "retrySubmit": "Ponów powiązanie",
    "uploadRequired": "Dodaj zdjęcie.",
    "reviewStatus": "Sprawdzamy Twoje zgłoszenie.",
    "progressStatus": "Pracujemy nad Twoim zgłoszeniem.",
    "holdStatus": "Zgłoszenie jest tymczasowo wstrzymane.",
    "waitingStatus": "Czekamy na Twoją odpowiedź.",
    "closedStatus": "Zgłoszenie zamknięte.",
    "createdStatus": "Zgłoszenie zarejestrowane",
    "noRequests": "Brak zgłoszeń w tym widoku.",
    "viewResponse": "Zobacz odpowiedź na czacie"
  },
  "tr": {
    "actions": "Yapmanız gerekenler",
    "notifications": "Yeni bildirimler",
    "history": "Tamamlanan işlemler",
    "materials": "Belgeler ve fotoğraf raporları",
    "latestRequests": "Son talepler",
    "emptyActions": "Şu anda yapmanız gereken bir işlem yok.",
    "emptyNotifications": "Yeni bildirim yok.",
    "emptyHistory": "Henüz tamamlanan işlem yok.",
    "emptyMaterials": "Henüz belge veya fotoğraf raporu yok.",
    "open": "Aç",
    "acknowledge": "Okudum",
    "markRead": "Okundu olarak işaretle",
    "reply": "Yanıtla",
    "upload": "Fotoğraf ekle",
    "submitted": "Gönderildi · inceleniyor",
    "completed": "Tamamlandı",
    "cancelled": "Geri çekildi",
    "due": "Son tarih",
    "loading": "Yükleniyor…",
    "error": "Güncellenemedi. Son yüklenen bilgiler gösteriliyor.",
    "retry": "Tekrar dene",
    "all": "Tümü",
    "unread": "Okunmamış",
    "saved": "Kaydedildi",
    "acknowledgeHint": "Bu onay yalnızca okuduğunuzu belirtir; ödeme, imza veya iş kabulü anlamına gelmez.",
    "status": "Talep durumu",
    "noAddress": "Adres belirtilmedi",
    "request": "Talep",
    "account": "Doğrulanmış müşteri hesabı",
    "DOCUMENT": "Belge",
    "REPORT": "Fotoğraf raporu",
    "REQUEST": "Yanıtınız",
    "MESSAGE": "Mesaj",
    "STATUS": "Durum güncellendi",
    "activeRequests": "Aktif talepler",
    "respondingTo": "Yanıtlanan talep",
    "cancelReply": "Yanıtı iptal et",
    "responseSaved": "Yanıt gönderildi",
    "responseLinkFailed": "Yanıt kaydedildi ancak bu işlemle henüz ilişkilendirilemedi.",
    "retrySubmit": "Tekrar ilişkilendir",
    "uploadRequired": "Lütfen fotoğraf ekleyin.",
    "reviewStatus": "Talebinizi inceliyoruz.",
    "progressStatus": "Talebiniz üzerinde çalışıyoruz.",
    "holdStatus": "Talep geçici olarak beklemede.",
    "waitingStatus": "Yanıtınızı bekliyoruz.",
    "closedStatus": "Talep kapatıldı.",
    "createdStatus": "Talep kaydedildi",
    "noRequests": "Bu görünümde talep yok.",
    "viewResponse": "Yanıtı sohbette görüntüle"
  },
  "ar": {
    "actions": "الإجراءات المطلوبة منك",
    "notifications": "إشعارات جديدة",
    "history": "الإجراءات المكتملة",
    "materials": "المستندات وتقارير الصور",
    "latestRequests": "أحدث الطلبات",
    "emptyActions": "لا يوجد إجراء مطلوب منك حاليًا.",
    "emptyNotifications": "لا توجد إشعارات جديدة.",
    "emptyHistory": "لا توجد إجراءات مكتملة بعد.",
    "emptyMaterials": "لا توجد مستندات أو تقارير صور بعد.",
    "open": "فتح",
    "acknowledge": "اطلعت عليه",
    "markRead": "تحديد كمقروء",
    "reply": "الرد",
    "upload": "إضافة صور",
    "submitted": "تم الإرسال · قيد المراجعة",
    "completed": "مكتمل",
    "cancelled": "تم السحب",
    "due": "الموعد النهائي",
    "loading": "جار التحميل…",
    "error": "تعذر التحديث. لا تزال آخر المعلومات المحملة ظاهرة.",
    "retry": "إعادة المحاولة",
    "all": "الكل",
    "unread": "غير مقروء",
    "saved": "تم الحفظ",
    "acknowledgeHint": "التأكيد يعني الاطلاع فقط، وليس الدفع أو التوقيع أو قبول الأعمال.",
    "status": "حالة الطلب",
    "noAddress": "لم يحدد العنوان",
    "request": "طلب",
    "account": "حساب عميل مؤكد",
    "DOCUMENT": "مستند",
    "REPORT": "تقرير صور",
    "REQUEST": "ردك",
    "MESSAGE": "رسالة",
    "STATUS": "تم تحديث الحالة",
    "activeRequests": "الطلبات النشطة",
    "respondingTo": "الرد على",
    "cancelReply": "إلغاء الرد",
    "responseSaved": "تم إرسال الرد",
    "responseLinkFailed": "تم حفظ الرد ولكن تعذر ربطه بهذا الإجراء بعد.",
    "retrySubmit": "إعادة محاولة الربط",
    "uploadRequired": "يرجى إضافة صورة.",
    "reviewStatus": "نراجع طلبك.",
    "progressStatus": "نعمل على طلبك.",
    "holdStatus": "الطلب معلق مؤقتًا.",
    "waitingStatus": "ننتظر ردك.",
    "closedStatus": "تم إغلاق الطلب.",
    "createdStatus": "تم تسجيل الطلب",
    "noRequests": "لا توجد طلبات في هذه القائمة.",
    "viewResponse": "عرض الرد في المحادثة"
  }
};
export function getAttentionCopy(locale?: string | null) { return copy[locale as keyof typeof copy] || copy.de; }
