type EmailCopy = { portal: string; document: string; report: string; request: string; update: string; body: string; open: string };
const copies: Record<string, EmailCopy> = {
  de: { portal: 'PixelRing Kundenportal', document: 'Neues Dokument', report: 'Neuer Fotobericht', request: 'Ihre Rückmeldung ist erforderlich', update: 'Neuigkeiten zu Ihrer Anfrage', body: 'In Ihrem Kundenportal gibt es Neuigkeiten zu dieser Anfrage. Öffnen Sie die Anfrage, um die Details und Ihre offenen Aufgaben zu sehen.', open: 'Anfrage im Kundenportal öffnen' },
  en: { portal: 'PixelRing customer portal', document: 'New document', report: 'New photo report', request: 'Your response is required', update: 'An update to your request', body: 'There is an update to this request in your customer portal. Open the request to see the details and your outstanding actions.', open: 'Open request in your portal' },
  ru: { portal: 'Личный кабинет PixelRing', document: 'Новый документ', report: 'Новый фотоотчёт', request: 'Требуется ваш ответ', update: 'Новости по вашей заявке', body: 'В личном кабинете появилась новая информация по этой заявке. Откройте заявку, чтобы посмотреть подробности и список ваших действий.', open: 'Открыть заявку в кабинете' },
  tr: { portal: 'PixelRing müşteri portalı', document: 'Yeni belge', report: 'Yeni fotoğraf raporu', request: 'Yanıtınız gerekiyor', update: 'Talebinizle ilgili güncelleme', body: 'Müşteri portalınızda bu taleple ilgili bir güncelleme var. Ayrıntıları ve bekleyen işlemlerinizi görmek için talebi açın.', open: 'Talebi müşteri portalında aç' },
  pl: { portal: 'Panel klienta PixelRing', document: 'Nowy dokument', report: 'Nowy raport fotograficzny', request: 'Potrzebna jest Twoja odpowiedź', update: 'Aktualizacja zgłoszenia', body: 'W panelu klienta pojawiły się nowe informacje dotyczące tego zgłoszenia. Otwórz zgłoszenie, aby zobaczyć szczegóły i oczekujące zadania.', open: 'Otwórz zgłoszenie w panelu' },
  ar: { portal: 'بوابة عملاء PixelRing', document: 'مستند جديد', report: 'تقرير صور جديد', request: 'ردك مطلوب', update: 'تحديث بشأن طلبك', body: 'توجد معلومات جديدة بشأن هذا الطلب في بوابة العميل. افتح الطلب للاطلاع على التفاصيل والإجراءات المطلوبة منك.', open: 'فتح الطلب في بوابة العميل' },
};
export function attentionEmailLocale(value?: string | null): string { return value && copies[value] ? value : 'de'; }
export function getAttentionEmailCopy(value?: string | null) { return copies[attentionEmailLocale(value)]; }
