ALTER TYPE "CmsArticleStatus" ADD VALUE IF NOT EXISTS 'IN_REVIEW';
ALTER TYPE "CmsArticleStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "CmsArticleStatus" ADD VALUE IF NOT EXISTS 'SCHEDULED';
ALTER TYPE "CmsArticleStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
