const COPY = {
  de: {
    common: {
      portal: 'Kundenportal',
      email: 'E-Mail-Adresse',
      password: 'Passwort',
      passwordRepeat: 'Passwort wiederholen',
      newPassword: 'Neues Passwort',
      codeFromEmail: 'Code aus der E-Mail',
      showPassword: 'Anzeigen',
      hidePassword: 'Ausblenden',
      showPasswordAria: 'Passwort anzeigen',
      hidePasswordAria: 'Passwort ausblenden',
      localCode: 'Lokaler Code:',
      dateLocale: 'de-DE',
    },
    claim: {
      apiFallback: 'Die Bestaetigung konnte nicht abgeschlossen werden.',
      grantError: 'Die Anfrage konnte nicht verbunden werden.',
      codeSent: 'Wir haben einen Code an Ihre E-Mail-Adresse gesendet.',
      startError: 'Die Bestaetigung konnte nicht gestartet werden.',
      emailConfirmed: 'E-Mail bestaetigt. Legen Sie jetzt Ihr Portal-Passwort fest.',
      invalidCode: 'Der Code ist ungueltig oder abgelaufen.',
      passwordError: 'Das Passwort konnte nicht gespeichert werden.',
      title: 'Anfrage sicher verbinden',
      body: 'Diese Seite verbindet genau diese Anfrage mit einer bestaetigten Portal-Identitaet. Die PR-Nummer allein oeffnet keine privaten Daten.',
      requestLabel: 'Anfrage',
      expiresLabel: 'Link gueltig bis',
      authenticatedEyebrow: 'Angemeldet',
      authenticatedTitle: 'Anfrage mit Ihrem Konto verbinden',
      authenticatedBody: 'Sie sind bereits im Kundenportal angemeldet. Nach der Bestaetigung wird nur diese Anfrage fuer Ihr Konto freigegeben.',
      connectLoading: 'Wird verbunden ...',
      connect: 'Anfrage verbinden',
      emailEyebrow: 'E-Mail-Code',
      emailTitle: 'Portal-Zugang aktivieren',
      emailBody: 'Geben Sie Ihre E-Mail ein, bestaetigen Sie den Code und legen Sie ein Passwort fest.',
      loginFirst: 'Schon ein Konto? Erst einloggen und diesen Link erneut oeffnen.',
      sendCodeLoading: 'Code wird gesendet ...',
      sendCode: 'Code senden',
      verifyCodeLoading: 'Code wird geprueft ...',
      verifyCode: 'Code bestaetigen',
      resendCode: 'Code erneut senden',
      createAndConnectLoading: 'Wird gespeichert ...',
      createAndConnect: 'Konto erstellen und Anfrage verbinden',
    },
    entry: {
      apiFallback: 'Die Aktion konnte nicht abgeschlossen werden.',
      loginError: 'E-Mail oder Passwort ist nicht korrekt.',
      codeSent: 'Wenn die E-Mail verwendet werden kann, senden wir einen Code an diese Adresse.',
      codeSendError: 'Der Code konnte nicht gesendet werden.',
      emailConfirmed: 'E-Mail bestaetigt. Legen Sie jetzt Ihr Passwort fest.',
      invalidCode: 'Der Code ist ungueltig oder abgelaufen.',
      passwordError: 'Das Passwort konnte nicht gespeichert werden.',
      demoError: 'Demo-Zugang konnte nicht geoeffnet werden.',
      title: 'Einloggen oder Kundenkonto erstellen',
      body: 'Registrieren Sie sich mit E-Mail-Code und eigenem Passwort. Bestehende Anfragen werden erst nach sicherer Kontaktpruefung verbunden.',
      steps: [
        { title: 'E-Mail-Code', text: 'Kein Login-Link im Postfach. Sie geben den Code hier auf der Website ein.' },
        { title: 'Eigenes Passwort', text: 'Das Passwort wird nie per E-Mail versendet und nur als Hash gespeichert.' },
        { title: 'Sicher verbunden', text: 'PR-Nummern oeffnen keine privaten Portal-Daten ohne zusaetzliche Pruefung.' },
      ],
      login: 'Einloggen',
      register: 'Registrieren',
      loginLoading: 'Wird geprueft ...',
      forgotPassword: 'Passwort vergessen?',
      resetTitle: 'Passwort zuruecksetzen',
      registerTitle: 'Konto erstellen',
      sendCodeLoading: 'Code wird gesendet ...',
      sendCode: 'Code senden',
      verifyCodeLoading: 'Code wird geprueft ...',
      verifyCode: 'Code bestaetigen',
      resendCode: 'Code erneut senden',
      saveLoading: 'Wird gespeichert ...',
      savePassword: 'Passwort speichern',
      createAccount: 'Konto erstellen',
      existingTitle: 'Bestehende Anfrage pruefen',
      existingText: 'Wenn Sie schon eine PR-Nummer haben, pruefen Sie den Status mit der Telefonnummer oder E-Mail aus der Anfrage.',
      existingLabel: 'Anfrage-Status pruefen',
      newTitle: 'Neue Anfrage starten',
      newText: 'Sie koennen den Service direkt starten. Die Anfrage bekommt erst nach Kontaktangabe eine PR-Nummer.',
      newLabel: 'Service starten',
      demoEyebrow: 'Lokaler Demo-Zugang',
      demoHint: 'Nur fuer lokale Tests. Demo-E-Mail: {email}',
      demoSubmit: 'Demo oeffnen',
    },
    invalidClaim: {
      title: 'Link nicht mehr aktiv',
      body: 'Dieser Link ist abgelaufen oder wurde ersetzt. Bitte fordern Sie ueber Ihren PixelRing Kontakt einen neuen Portal-Link an.',
    },
    claimVerify: {
      title: 'Bestaetigungslink nicht mehr aktiv',
      body: 'Die Anfrage-Verbindung nutzt jetzt einen E-Mail-Code auf der Website. Bitte oeffnen Sie den aktuellen Portal-Link zur Anfrage erneut.',
      button: 'Zum Kundenportal',
    },
    loginVerify: {
      title: 'Login-Link nicht mehr aktiv',
      body: 'Das Kundenportal nutzt jetzt E-Mail-Code und Passwort. Bitte starten Sie den Login erneut.',
      button: 'Zum Kundenportal',
    },
    accessRequired: {
      title: 'E-Mail-Bestaetigung erforderlich',
      body: 'Der Zugang zum Kundenportal wird ueber den Portal-Link aus Ihrer Anfrage und eine bestaetigte E-Mail-Adresse aktiviert.',
      button: 'Anfrage-Status pruefen',
    },
  },
  en: {
    common: {
      portal: 'Customer portal',
      email: 'Email address',
      password: 'Password',
      passwordRepeat: 'Repeat password',
      newPassword: 'New password',
      codeFromEmail: 'Code from email',
      showPassword: 'Show',
      hidePassword: 'Hide',
      showPasswordAria: 'Show password',
      hidePasswordAria: 'Hide password',
      localCode: 'Local code:',
      dateLocale: 'en-US',
    },
    claim: {
      apiFallback: 'Verification could not be completed.',
      grantError: 'The request could not be connected.',
      codeSent: 'We sent a code to your email address.',
      startError: 'Verification could not be started.',
      emailConfirmed: 'Email confirmed. Set your portal password now.',
      invalidCode: 'The code is invalid or expired.',
      passwordError: 'The password could not be saved.',
      title: 'Connect this request securely',
      body: 'This page connects this exact request with a verified portal identity. The PR number alone does not open private data.',
      requestLabel: 'Request',
      expiresLabel: 'Link valid until',
      authenticatedEyebrow: 'Signed in',
      authenticatedTitle: 'Connect the request to your account',
      authenticatedBody: 'You are already signed in to the customer portal. After confirmation, only this request will be added to your account.',
      connectLoading: 'Connecting ...',
      connect: 'Connect request',
      emailEyebrow: 'Email code',
      emailTitle: 'Activate portal access',
      emailBody: 'Enter your email, confirm the code, and set a password.',
      loginFirst: 'Already have an account? Sign in first and open this link again.',
      sendCodeLoading: 'Sending code ...',
      sendCode: 'Send code',
      verifyCodeLoading: 'Checking code ...',
      verifyCode: 'Confirm code',
      resendCode: 'Send code again',
      createAndConnectLoading: 'Saving ...',
      createAndConnect: 'Create account and connect request',
    },
    entry: {
      apiFallback: 'The action could not be completed.',
      loginError: 'Email or password is not correct.',
      codeSent: 'If the email can be used, we will send a code to that address.',
      codeSendError: 'The code could not be sent.',
      emailConfirmed: 'Email confirmed. Set your password now.',
      invalidCode: 'The code is invalid or expired.',
      passwordError: 'The password could not be saved.',
      demoError: 'Demo access could not be opened.',
      title: 'Sign in or create a customer account',
      body: 'Register with an email code and your own password. Existing requests are connected only after secure contact verification.',
      steps: [
        { title: 'Email code', text: 'No login link in your inbox. You enter the code here on the website.' },
        { title: 'Own password', text: 'The password is never sent by email and is stored only as a hash.' },
        { title: 'Securely connected', text: 'PR numbers do not open private portal data without an additional check.' },
      ],
      login: 'Sign in',
      register: 'Register',
      loginLoading: 'Checking ...',
      forgotPassword: 'Forgot password?',
      resetTitle: 'Reset password',
      registerTitle: 'Create account',
      sendCodeLoading: 'Sending code ...',
      sendCode: 'Send code',
      verifyCodeLoading: 'Checking code ...',
      verifyCode: 'Confirm code',
      resendCode: 'Send code again',
      saveLoading: 'Saving ...',
      savePassword: 'Save password',
      createAccount: 'Create account',
      existingTitle: 'Check an existing request',
      existingText: 'If you already have a PR number, check the status with the phone or email used for the request.',
      existingLabel: 'Check request status',
      newTitle: 'Start a new request',
      newText: 'You can start the service directly. The request receives a PR number only after contact details are provided.',
      newLabel: 'Start service',
      demoEyebrow: 'Local demo access',
      demoHint: 'For local testing only. Demo email: {email}',
      demoSubmit: 'Open demo',
    },
    invalidClaim: {
      title: 'Link no longer active',
      body: 'This link has expired or was replaced. Please ask your PixelRing contact for a new portal link.',
    },
    claimVerify: {
      title: 'Confirmation link no longer active',
      body: 'Request linking now uses an email code on the website. Please open the current portal link for the request again.',
      button: 'Go to customer portal',
    },
    loginVerify: {
      title: 'Login link no longer active',
      body: 'The customer portal now uses email code and password. Please start login again.',
      button: 'Go to customer portal',
    },
    accessRequired: {
      title: 'Email confirmation required',
      body: 'Customer portal access is activated through the portal link from your request and a confirmed email address.',
      button: 'Check request status',
    },
  },
  ru: {
    common: {
      portal: 'Личный кабинет',
      email: 'E-mail',
      password: 'Пароль',
      passwordRepeat: 'Повторите пароль',
      newPassword: 'Новый пароль',
      codeFromEmail: 'Код из e-mail',
      showPassword: 'Показать',
      hidePassword: 'Скрыть',
      showPasswordAria: 'Показать пароль',
      hidePasswordAria: 'Скрыть пароль',
      localCode: 'Локальный код:',
      dateLocale: 'ru-RU',
    },
    claim: {
      apiFallback: 'Не удалось завершить подтверждение.',
      grantError: 'Не удалось привязать заявку.',
      codeSent: 'Мы отправили код на ваш e-mail.',
      startError: 'Не удалось начать подтверждение.',
      emailConfirmed: 'E-mail подтвержден. Теперь задайте пароль для кабинета.',
      invalidCode: 'Код неверный или истек.',
      passwordError: 'Не удалось сохранить пароль.',
      title: 'Безопасно привязать заявку',
      body: 'Эта страница привязывает именно эту заявку к подтвержденному кабинету. Один PR-номер не открывает приватные данные.',
      requestLabel: 'Заявка',
      expiresLabel: 'Ссылка активна до',
      authenticatedEyebrow: 'Вход выполнен',
      authenticatedTitle: 'Привязать заявку к вашему аккаунту',
      authenticatedBody: 'Вы уже вошли в личный кабинет. После подтверждения к аккаунту будет добавлена только эта заявка.',
      connectLoading: 'Привязываем ...',
      connect: 'Привязать заявку',
      emailEyebrow: 'Код по e-mail',
      emailTitle: 'Активировать доступ в кабинет',
      emailBody: 'Введите e-mail, подтвердите код и задайте пароль.',
      loginFirst: 'Уже есть аккаунт? Сначала войдите и откройте эту ссылку снова.',
      sendCodeLoading: 'Отправляем код ...',
      sendCode: 'Отправить код',
      verifyCodeLoading: 'Проверяем код ...',
      verifyCode: 'Подтвердить код',
      resendCode: 'Отправить код еще раз',
      createAndConnectLoading: 'Сохраняем ...',
      createAndConnect: 'Создать аккаунт и привязать заявку',
    },
    entry: {
      apiFallback: 'Не удалось выполнить действие.',
      loginError: 'E-mail или пароль неверны.',
      codeSent: 'Если этот e-mail можно использовать, мы отправим на него код.',
      codeSendError: 'Не удалось отправить код.',
      emailConfirmed: 'E-mail подтвержден. Теперь задайте пароль.',
      invalidCode: 'Код неверный или истек.',
      passwordError: 'Не удалось сохранить пароль.',
      demoError: 'Не удалось открыть демо-доступ.',
      title: 'Войдите или создайте личный кабинет',
      body: 'Зарегистрируйтесь через код по e-mail и собственный пароль. Существующие заявки подключаются только после безопасной проверки контакта.',
      steps: [
        { title: 'Код по e-mail', text: 'В письме нет login-link. Код вводится здесь, на сайте.' },
        { title: 'Собственный пароль', text: 'Пароль не отправляется по e-mail и хранится только как hash.' },
        { title: 'Безопасная привязка', text: 'PR-номер не открывает приватные данные кабинета без дополнительной проверки.' },
      ],
      login: 'Войти',
      register: 'Регистрация',
      loginLoading: 'Проверяем ...',
      forgotPassword: 'Забыли пароль?',
      resetTitle: 'Сбросить пароль',
      registerTitle: 'Создать аккаунт',
      sendCodeLoading: 'Отправляем код ...',
      sendCode: 'Отправить код',
      verifyCodeLoading: 'Проверяем код ...',
      verifyCode: 'Подтвердить код',
      resendCode: 'Отправить код еще раз',
      saveLoading: 'Сохраняем ...',
      savePassword: 'Сохранить пароль',
      createAccount: 'Создать аккаунт',
      existingTitle: 'Проверить существующую заявку',
      existingText: 'Если у вас уже есть PR-номер, проверьте статус по телефону или e-mail, указанному в заявке.',
      existingLabel: 'Проверить статус заявки',
      newTitle: 'Начать новую заявку',
      newText: 'Вы можете сразу начать сервисный запрос. PR-номер появится после указания контактных данных.',
      newLabel: 'Начать заявку',
      demoEyebrow: 'Локальный демо-доступ',
      demoHint: 'Только для локальных тестов. Demo e-mail: {email}',
      demoSubmit: 'Открыть demo',
    },
    invalidClaim: {
      title: 'Ссылка больше не активна',
      body: 'Эта ссылка истекла или была заменена. Запросите новую ссылку кабинета у вашего контакта PixelRing.',
    },
    claimVerify: {
      title: 'Ссылка подтверждения больше не активна',
      body: 'Привязка заявки теперь использует код по e-mail на сайте. Откройте актуальную ссылку кабинета для этой заявки еще раз.',
      button: 'В личный кабинет',
    },
    loginVerify: {
      title: 'Login-link больше не активен',
      body: 'Клиентский кабинет теперь использует код по e-mail и пароль. Начните вход заново.',
      button: 'В личный кабинет',
    },
    accessRequired: {
      title: 'Требуется подтверждение e-mail',
      body: 'Доступ в личный кабинет активируется через ссылку из вашей заявки и подтвержденный e-mail.',
      button: 'Проверить статус заявки',
    },
  },
  tr: {
    common: {
      portal: 'Musteri portali',
      email: 'E-posta adresi',
      password: 'Sifre',
      passwordRepeat: 'Sifreyi tekrarla',
      newPassword: 'Yeni sifre',
      codeFromEmail: 'E-postadaki kod',
      showPassword: 'Goster',
      hidePassword: 'Gizle',
      showPasswordAria: 'Sifreyi goster',
      hidePasswordAria: 'Sifreyi gizle',
      localCode: 'Yerel kod:',
      dateLocale: 'tr-TR',
    },
    claim: {
      apiFallback: 'Dogrulama tamamlanamadi.',
      grantError: 'Talep baglanamadi.',
      codeSent: 'E-posta adresinize bir kod gonderdik.',
      startError: 'Dogrulama baslatilamadi.',
      emailConfirmed: 'E-posta dogrulandi. Simdi portal sifrenizi belirleyin.',
      invalidCode: 'Kod gecersiz veya suresi dolmus.',
      passwordError: 'Sifre kaydedilemedi.',
      title: 'Talebi guvenli sekilde baglayin',
      body: 'Bu sayfa tam olarak bu talebi dogrulanmis bir portal kimligine baglar. PR numarasi tek basina ozel verileri acmaz.',
      requestLabel: 'Talep',
      expiresLabel: 'Baglanti gecerlilik sonu',
      authenticatedEyebrow: 'Giris yapildi',
      authenticatedTitle: 'Talebi hesabiniza baglayin',
      authenticatedBody: 'Musteri portalinda zaten oturum actiniz. Onaydan sonra hesabiniza yalnizca bu talep eklenir.',
      connectLoading: 'Baglaniyor ...',
      connect: 'Talebi bagla',
      emailEyebrow: 'E-posta kodu',
      emailTitle: 'Portal erisimini etkinlestir',
      emailBody: 'E-postanizi girin, kodu dogrulayin ve bir sifre belirleyin.',
      loginFirst: 'Zaten hesabiniz var mi? Once giris yapin ve bu baglantiyi tekrar acin.',
      sendCodeLoading: 'Kod gonderiliyor ...',
      sendCode: 'Kodu gonder',
      verifyCodeLoading: 'Kod kontrol ediliyor ...',
      verifyCode: 'Kodu onayla',
      resendCode: 'Kodu tekrar gonder',
      createAndConnectLoading: 'Kaydediliyor ...',
      createAndConnect: 'Hesap olustur ve talebi bagla',
    },
    entry: {
      apiFallback: 'Islem tamamlanamadi.',
      loginError: 'E-posta veya sifre dogru degil.',
      codeSent: 'E-posta kullanilabiliyorsa bu adrese bir kod gonderecegiz.',
      codeSendError: 'Kod gonderilemedi.',
      emailConfirmed: 'E-posta dogrulandi. Simdi sifrenizi belirleyin.',
      invalidCode: 'Kod gecersiz veya suresi dolmus.',
      passwordError: 'Sifre kaydedilemedi.',
      demoError: 'Demo erisimi acilamadi.',
      title: 'Giris yapin veya musteri hesabi olusturun',
      body: 'E-posta kodu ve kendi sifrenizle kaydolun. Mevcut talepler yalnizca guvenli iletisim dogrulamasindan sonra baglanir.',
      steps: [
        { title: 'E-posta kodu', text: 'Posta kutusunda login link yok. Kodu burada, web sitesinde girersiniz.' },
        { title: 'Kendi sifreniz', text: 'Sifre e-posta ile gonderilmez ve yalnizca hash olarak saklanir.' },
        { title: 'Guvenli baglanti', text: 'PR numaralari ek kontrol olmadan ozel portal verilerini acmaz.' },
      ],
      login: 'Giris yap',
      register: 'Kaydol',
      loginLoading: 'Kontrol ediliyor ...',
      forgotPassword: 'Sifrenizi mi unuttunuz?',
      resetTitle: 'Sifreyi sifirla',
      registerTitle: 'Hesap olustur',
      sendCodeLoading: 'Kod gonderiliyor ...',
      sendCode: 'Kodu gonder',
      verifyCodeLoading: 'Kod kontrol ediliyor ...',
      verifyCode: 'Kodu onayla',
      resendCode: 'Kodu tekrar gonder',
      saveLoading: 'Kaydediliyor ...',
      savePassword: 'Sifreyi kaydet',
      createAccount: 'Hesap olustur',
      existingTitle: 'Mevcut talebi kontrol et',
      existingText: 'Zaten bir PR numaraniz varsa, talepte kullanilan telefon veya e-posta ile durumu kontrol edin.',
      existingLabel: 'Talep durumunu kontrol et',
      newTitle: 'Yeni talep baslat',
      newText: 'Servisi dogrudan baslatabilirsiniz. Talep, iletisim bilgileri verildikten sonra PR numarasi alir.',
      newLabel: 'Servisi baslat',
      demoEyebrow: 'Yerel demo erisimi',
      demoHint: 'Yalnizca yerel test icin. Demo e-posta: {email}',
      demoSubmit: 'Demoyu ac',
    },
    invalidClaim: {
      title: 'Baglanti artik aktif degil',
      body: 'Bu baglantinin suresi doldu veya degistirildi. Lutfen PixelRing iletisiminizden yeni bir portal baglantisi isteyin.',
    },
    claimVerify: {
      title: 'Onay baglantisi artik aktif degil',
      body: 'Talep baglama artik web sitesindeki e-posta kodunu kullanir. Lutfen talep icin guncel portal baglantisini tekrar acin.',
      button: 'Musteri portalina git',
    },
    loginVerify: {
      title: 'Giris baglantisi artik aktif degil',
      body: 'Musteri portali artik e-posta kodu ve sifre kullanir. Lutfen girisi yeniden baslatin.',
      button: 'Musteri portalina git',
    },
    accessRequired: {
      title: 'E-posta onayi gerekli',
      body: 'Musteri portali erisimi, talebinizdeki portal baglantisi ve onaylanmis e-posta adresi ile etkinlestirilir.',
      button: 'Talep durumunu kontrol et',
    },
  },
  pl: {
    common: {
      portal: 'Portal klienta',
      email: 'Adres e-mail',
      password: 'Haslo',
      passwordRepeat: 'Powtorz haslo',
      newPassword: 'Nowe haslo',
      codeFromEmail: 'Kod z e-maila',
      showPassword: 'Pokaz',
      hidePassword: 'Ukryj',
      showPasswordAria: 'Pokaz haslo',
      hidePasswordAria: 'Ukryj haslo',
      localCode: 'Kod lokalny:',
      dateLocale: 'pl-PL',
    },
    claim: {
      apiFallback: 'Nie udalo sie zakonczyc weryfikacji.',
      grantError: 'Nie udalo sie polaczyc zgloszenia.',
      codeSent: 'Wyslalismy kod na Twoj adres e-mail.',
      startError: 'Nie udalo sie rozpoczac weryfikacji.',
      emailConfirmed: 'E-mail potwierdzony. Ustaw teraz haslo do portalu.',
      invalidCode: 'Kod jest nieprawidlowy albo wygasl.',
      passwordError: 'Nie udalo sie zapisac hasla.',
      title: 'Bezpiecznie polacz zgloszenie',
      body: 'Ta strona laczy dokladnie to zgloszenie ze zweryfikowana tozsamoscia w portalu. Sam numer PR nie otwiera danych prywatnych.',
      requestLabel: 'Zgloszenie',
      expiresLabel: 'Link wazny do',
      authenticatedEyebrow: 'Zalogowano',
      authenticatedTitle: 'Polacz zgloszenie z kontem',
      authenticatedBody: 'Jestes juz zalogowany w portalu klienta. Po potwierdzeniu do konta zostanie dodane tylko to zgloszenie.',
      connectLoading: 'Laczenie ...',
      connect: 'Polacz zgloszenie',
      emailEyebrow: 'Kod e-mail',
      emailTitle: 'Aktywuj dostep do portalu',
      emailBody: 'Wpisz e-mail, potwierdz kod i ustaw haslo.',
      loginFirst: 'Masz juz konto? Najpierw sie zaloguj i otworz ten link ponownie.',
      sendCodeLoading: 'Wysylanie kodu ...',
      sendCode: 'Wyslij kod',
      verifyCodeLoading: 'Sprawdzanie kodu ...',
      verifyCode: 'Potwierdz kod',
      resendCode: 'Wyslij kod ponownie',
      createAndConnectLoading: 'Zapisywanie ...',
      createAndConnect: 'Utworz konto i polacz zgloszenie',
    },
    entry: {
      apiFallback: 'Nie udalo sie zakonczyc akcji.',
      loginError: 'E-mail albo haslo jest nieprawidlowe.',
      codeSent: 'Jesli e-mail moze zostac uzyty, wyslemy kod na ten adres.',
      codeSendError: 'Nie udalo sie wyslac kodu.',
      emailConfirmed: 'E-mail potwierdzony. Ustaw teraz haslo.',
      invalidCode: 'Kod jest nieprawidlowy albo wygasl.',
      passwordError: 'Nie udalo sie zapisac hasla.',
      demoError: 'Nie udalo sie otworzyc dostepu demo.',
      title: 'Zaloguj sie albo utworz konto klienta',
      body: 'Zarejestruj sie za pomoca kodu e-mail i wlasnego hasla. Istniejace zgloszenia sa laczone dopiero po bezpiecznej weryfikacji kontaktu.',
      steps: [
        { title: 'Kod e-mail', text: 'W skrzynce nie ma linku logowania. Kod wpisujesz tutaj na stronie.' },
        { title: 'Wlasne haslo', text: 'Haslo nigdy nie jest wysylane e-mailem i jest przechowywane tylko jako hash.' },
        { title: 'Bezpieczne polaczenie', text: 'Numery PR nie otwieraja prywatnych danych portalu bez dodatkowej kontroli.' },
      ],
      login: 'Zaloguj sie',
      register: 'Rejestracja',
      loginLoading: 'Sprawdzanie ...',
      forgotPassword: 'Nie pamietasz hasla?',
      resetTitle: 'Resetuj haslo',
      registerTitle: 'Utworz konto',
      sendCodeLoading: 'Wysylanie kodu ...',
      sendCode: 'Wyslij kod',
      verifyCodeLoading: 'Sprawdzanie kodu ...',
      verifyCode: 'Potwierdz kod',
      resendCode: 'Wyslij kod ponownie',
      saveLoading: 'Zapisywanie ...',
      savePassword: 'Zapisz haslo',
      createAccount: 'Utworz konto',
      existingTitle: 'Sprawdz istniejace zgloszenie',
      existingText: 'Jesli masz juz numer PR, sprawdz status telefonem lub e-mailem uzytym w zgloszeniu.',
      existingLabel: 'Sprawdz status zgloszenia',
      newTitle: 'Rozpocznij nowe zgloszenie',
      newText: 'Mozesz od razu rozpoczac obsluge. Zgloszenie otrzyma numer PR dopiero po podaniu danych kontaktowych.',
      newLabel: 'Rozpocznij obsluge',
      demoEyebrow: 'Lokalny dostep demo',
      demoHint: 'Tylko do testow lokalnych. E-mail demo: {email}',
      demoSubmit: 'Otworz demo',
    },
    invalidClaim: {
      title: 'Link nie jest juz aktywny',
      body: 'Ten link wygasl albo zostal zastapiony. Popros kontakt PixelRing o nowy link do portalu.',
    },
    claimVerify: {
      title: 'Link potwierdzajacy nie jest juz aktywny',
      body: 'Laczenie zgloszenia uzywa teraz kodu e-mail na stronie. Otworz ponownie aktualny link portalu dla tego zgloszenia.',
      button: 'Do portalu klienta',
    },
    loginVerify: {
      title: 'Link logowania nie jest juz aktywny',
      body: 'Portal klienta uzywa teraz kodu e-mail i hasla. Rozpocznij logowanie ponownie.',
      button: 'Do portalu klienta',
    },
    accessRequired: {
      title: 'Wymagane potwierdzenie e-mail',
      body: 'Dostep do portalu klienta aktywuje sie przez link portalu z Twojego zgloszenia i potwierdzony adres e-mail.',
      button: 'Sprawdz status zgloszenia',
    },
  },
  ar: {
    common: {
      portal: 'بوابة العميل',
      email: 'البريد الإلكتروني',
      password: 'كلمة المرور',
      passwordRepeat: 'تكرار كلمة المرور',
      newPassword: 'كلمة مرور جديدة',
      codeFromEmail: 'الرمز من البريد الإلكتروني',
      showPassword: 'إظهار',
      hidePassword: 'إخفاء',
      showPasswordAria: 'إظهار كلمة المرور',
      hidePasswordAria: 'إخفاء كلمة المرور',
      localCode: 'الرمز المحلي:',
      dateLocale: 'ar',
    },
    claim: {
      apiFallback: 'تعذر إكمال التحقق.',
      grantError: 'تعذر ربط الطلب.',
      codeSent: 'أرسلنا رمزاً إلى بريدك الإلكتروني.',
      startError: 'تعذر بدء التحقق.',
      emailConfirmed: 'تم تأكيد البريد الإلكتروني. عيّن الآن كلمة مرور البوابة.',
      invalidCode: 'الرمز غير صحيح أو انتهت صلاحيته.',
      passwordError: 'تعذر حفظ كلمة المرور.',
      title: 'ربط الطلب بأمان',
      body: 'هذه الصفحة تربط هذا الطلب المحدد بهوية مؤكدة في البوابة. رقم PR وحده لا يفتح البيانات الخاصة.',
      requestLabel: 'الطلب',
      expiresLabel: 'الرابط صالح حتى',
      authenticatedEyebrow: 'تم تسجيل الدخول',
      authenticatedTitle: 'ربط الطلب بحسابك',
      authenticatedBody: 'أنت مسجل الدخول بالفعل في بوابة العميل. بعد التأكيد سيضاف هذا الطلب فقط إلى حسابك.',
      connectLoading: 'جار الربط ...',
      connect: 'ربط الطلب',
      emailEyebrow: 'رمز البريد الإلكتروني',
      emailTitle: 'تفعيل الوصول إلى البوابة',
      emailBody: 'أدخل بريدك الإلكتروني، أكد الرمز، ثم عيّن كلمة مرور.',
      loginFirst: 'لديك حساب بالفعل؟ سجل الدخول أولاً ثم افتح هذا الرابط مرة أخرى.',
      sendCodeLoading: 'جار إرسال الرمز ...',
      sendCode: 'إرسال الرمز',
      verifyCodeLoading: 'جار فحص الرمز ...',
      verifyCode: 'تأكيد الرمز',
      resendCode: 'إرسال الرمز مرة أخرى',
      createAndConnectLoading: 'جار الحفظ ...',
      createAndConnect: 'إنشاء الحساب وربط الطلب',
    },
    entry: {
      apiFallback: 'تعذر إكمال الإجراء.',
      loginError: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
      codeSent: 'إذا كان يمكن استخدام البريد الإلكتروني، سنرسل رمزاً إلى هذا العنوان.',
      codeSendError: 'تعذر إرسال الرمز.',
      emailConfirmed: 'تم تأكيد البريد الإلكتروني. عيّن الآن كلمة المرور.',
      invalidCode: 'الرمز غير صحيح أو انتهت صلاحيته.',
      passwordError: 'تعذر حفظ كلمة المرور.',
      demoError: 'تعذر فتح الوصول التجريبي.',
      title: 'تسجيل الدخول أو إنشاء حساب عميل',
      body: 'سجّل باستخدام رمز البريد الإلكتروني وكلمة مرور خاصة بك. لا يتم ربط الطلبات الحالية إلا بعد تحقق آمن من بيانات الاتصال.',
      steps: [
        { title: 'رمز البريد الإلكتروني', text: 'لا يوجد رابط تسجيل دخول في البريد. تدخل الرمز هنا على الموقع.' },
        { title: 'كلمة مرور خاصة', text: 'لا تُرسل كلمة المرور بالبريد الإلكتروني وتُحفظ فقط كقيمة hash.' },
        { title: 'ربط آمن', text: 'أرقام PR لا تفتح بيانات البوابة الخاصة من دون تحقق إضافي.' },
      ],
      login: 'تسجيل الدخول',
      register: 'تسجيل',
      loginLoading: 'جار التحقق ...',
      forgotPassword: 'هل نسيت كلمة المرور؟',
      resetTitle: 'إعادة تعيين كلمة المرور',
      registerTitle: 'إنشاء حساب',
      sendCodeLoading: 'جار إرسال الرمز ...',
      sendCode: 'إرسال الرمز',
      verifyCodeLoading: 'جار فحص الرمز ...',
      verifyCode: 'تأكيد الرمز',
      resendCode: 'إرسال الرمز مرة أخرى',
      saveLoading: 'جار الحفظ ...',
      savePassword: 'حفظ كلمة المرور',
      createAccount: 'إنشاء حساب',
      existingTitle: 'التحقق من طلب قائم',
      existingText: 'إذا كان لديك رقم PR بالفعل، فتحقق من الحالة باستخدام الهاتف أو البريد الإلكتروني المستخدم في الطلب.',
      existingLabel: 'التحقق من حالة الطلب',
      newTitle: 'بدء طلب جديد',
      newText: 'يمكنك بدء الخدمة مباشرة. يحصل الطلب على رقم PR فقط بعد تقديم بيانات الاتصال.',
      newLabel: 'بدء الخدمة',
      demoEyebrow: 'وصول demo محلي',
      demoHint: 'للاختبار المحلي فقط. بريد demo: {email}',
      demoSubmit: 'فتح demo',
    },
    invalidClaim: {
      title: 'الرابط لم يعد نشطاً',
      body: 'انتهت صلاحية هذا الرابط أو تم استبداله. يرجى طلب رابط بوابة جديد من جهة اتصالك في PixelRing.',
    },
    claimVerify: {
      title: 'رابط التأكيد لم يعد نشطاً',
      body: 'ربط الطلب يستخدم الآن رمز البريد الإلكتروني على الموقع. يرجى فتح رابط البوابة الحالي لهذا الطلب مرة أخرى.',
      button: 'إلى بوابة العميل',
    },
    loginVerify: {
      title: 'رابط تسجيل الدخول لم يعد نشطاً',
      body: 'تستخدم بوابة العميل الآن رمز البريد الإلكتروني وكلمة المرور. يرجى بدء تسجيل الدخول مرة أخرى.',
      button: 'إلى بوابة العميل',
    },
    accessRequired: {
      title: 'تأكيد البريد الإلكتروني مطلوب',
      body: 'يتم تفعيل الوصول إلى بوابة العميل من خلال رابط البوابة في طلبك وبريد إلكتروني مؤكد.',
      button: 'التحقق من حالة الطلب',
    },
  },
} as const;

export type PortalStandaloneLocale = keyof typeof COPY;

export function getPortalStandaloneCopy(locale?: string | null) {
  return COPY[locale as PortalStandaloneLocale] ?? COPY.de;
}
