import type { PortalDemoOrganization } from './types';

export const PORTAL_DEMO_EMAIL_DEFAULT = 'pr-portal@pixel-ring.com';

export const portalDemoOrganization: PortalDemoOrganization = {
  id: 'demo-org-pixel-ring',
  name: 'Pixel Ring GmbH',
  plan: 'Growth',
  demoEmail: PORTAL_DEMO_EMAIL_DEFAULT,
  languagePreference: 'de',
  contacts: [
    {
      id: 'contact-ops',
      name: 'Mara Stein',
      role: 'Operations Manager',
      email: 'operations@pixel-ring.example',
      phone: '+49 30 000000-10',
    },
    {
      id: 'contact-facility',
      name: 'Anton Weber',
      role: 'Facility Lead',
      email: 'facility@pixel-ring.example',
      phone: '+49 30 000000-20',
    },
  ],
  objects: [
    {
      id: 'obj-showroom-berlin',
      name: 'Pixel Ring Showroom Berlin',
      city: 'Berlin',
      address: 'Demoallee 18, 10115 Berlin',
      purpose: 'Showroom und Beratungsfläche für Kundenbesuche.',
      accessNotes: 'Zugang nach 18:00 Uhr nur mit Empfangsfreigabe.',
      responsibleContactIds: ['contact-ops'],
    },
    {
      id: 'obj-service-hub-potsdam',
      name: 'Pixel Ring Service Hub Potsdam',
      city: 'Potsdam',
      address: 'Werkstraße 7, 14467 Potsdam',
      purpose: 'Werkstatt, Lager und Dispatch für Serviceeinsätze.',
      accessNotes: 'Anlieferung über Tor B, Sicherheitsweste erforderlich.',
      responsibleContactIds: ['contact-facility'],
    },
  ],
  assets: [
    {
      id: 'asset-showroom-sign',
      objectId: 'obj-showroom-berlin',
      name: 'Außenleuchtschild PixelRing',
      category: 'Leuchtwerbung',
      type: 'LED-Profilbuchstaben',
      status: 'SERVICE_NEEDED',
      serviceRelevance: 'Aktiver Netzteilfehler, Sichtbarkeit abends eingeschränkt.',
      lastServiceAt: '2026-03-18',
    },
    {
      id: 'asset-showroom-window',
      objectId: 'obj-showroom-berlin',
      name: 'Schaufensterfolierung Beratung',
      category: 'Folierung',
      type: 'Glasflächen-Set',
      status: 'OK',
      serviceRelevance: 'Erneuert nach Kampagnenwechsel.',
      lastServiceAt: '2026-04-09',
    },
    {
      id: 'asset-showroom-wayfinding',
      objectId: 'obj-showroom-berlin',
      name: 'Indoor-Wegweiser',
      category: 'Innenbeschilderung',
      type: 'Acryl- und Türschilder',
      status: 'WATCH',
      serviceRelevance: 'Nächster Audit prüft Pfeilführung und Befestigung.',
      lastServiceAt: '2026-02-22',
    },
    {
      id: 'asset-hub-bay-labels',
      objectId: 'obj-service-hub-potsdam',
      name: 'Lager- und Torbeschriftung',
      category: 'Betriebskennzeichnung',
      type: 'Bay Labels',
      status: 'SERVICE_NEEDED',
      serviceRelevance: 'Beschädigte Beschriftung an Tor B muss ersetzt werden.',
      lastServiceAt: '2026-01-31',
    },
    {
      id: 'asset-hub-banner',
      objectId: 'obj-service-hub-potsdam',
      name: 'Lokale Kampagnenbanner',
      category: 'Kampagnenmaterial',
      type: 'PVC-Banner-Set',
      status: 'OK',
      serviceRelevance: 'Nachbestellung abgeschlossen.',
      lastServiceAt: '2026-04-12',
    },
    {
      id: 'asset-hub-light-module',
      objectId: 'obj-service-hub-potsdam',
      name: 'Werkstatt-Außenlichtmodul',
      category: 'Leuchtwerbung',
      type: 'LED-Lichtmodul',
      status: 'WARRANTY',
      serviceRelevance: 'Garantiebezogene Reparatur dokumentiert.',
      lastServiceAt: '2026-03-28',
    },
  ],
  requests: [
    {
      id: 'request-showroom-power',
      publicRequestNumber: 'PR-DEMO-4821',
      objectId: 'obj-showroom-berlin',
      title: 'Netzteilprüfung Außenleuchtschild',
      status: 'WAITING_FOR_CUSTOMER',
      priority: 'high',
      openedAt: '2026-04-22',
      updatedAt: '2026-04-28',
      summary: 'Ein Teil der Profilbuchstaben fällt nach Sonnenuntergang aus.',
      nextStep: 'Kostenschätzung freigeben und gewünschtes Technikerfenster bestätigen.',
    },
    {
      id: 'request-window-refresh',
      publicRequestNumber: 'PR-DEMO-4730',
      objectId: 'obj-showroom-berlin',
      title: 'Schaufensterfolierung erneuert',
      status: 'COMPLETED',
      priority: 'normal',
      openedAt: '2026-04-04',
      updatedAt: '2026-04-09',
      summary: 'Saisonale Folien wurden ersetzt und die Glasflächen gereinigt.',
      nextStep: 'Foto-Report liegt zur internen Freigabe bereit.',
    },
    {
      id: 'request-hub-label',
      publicRequestNumber: 'PR-DEMO-4894',
      objectId: 'obj-service-hub-potsdam',
      title: 'Beschädigte Torbeschriftung ersetzen',
      status: 'UNDER_REVIEW',
      priority: 'normal',
      openedAt: '2026-04-26',
      updatedAt: '2026-04-28',
      summary: 'Bay Label an Tor B ist beschädigt und für Fahrer schlecht lesbar.',
      nextStep: 'Ein Detailfoto der beschädigten Kante nachreichen, damit die Vorlage bestätigt werden kann.',
    },
    {
      id: 'request-light-warranty',
      publicRequestNumber: 'PR-DEMO-4612',
      objectId: 'obj-service-hub-potsdam',
      title: 'Garantiereparatur Lichtmodul',
      status: 'COMPLETED',
      priority: 'normal',
      openedAt: '2026-03-21',
      updatedAt: '2026-03-28',
      summary: 'Defektes Lichtmodul wurde im Garantiezeitraum ausgetauscht.',
      nextStep: 'Garantiebeleg bleibt im Portal als Vorschau sichtbar.',
    },
  ],
  messages: [
    {
      id: 'msg-1',
      requestId: 'request-showroom-power',
      author: 'PixelRing AI',
      sentAt: '2026-04-22 08:18',
      body: 'Danke, die Fotos zeigen einen Ausfall einzelner Profilbuchstaben. Ich habe die Anfrage für eine technische Prüfung vorbereitet.',
    },
    {
      id: 'msg-2',
      requestId: 'request-showroom-power',
      author: 'Customer',
      sentAt: '2026-04-22 08:41',
      body: 'Der Ausfall ist vor allem abends sichtbar. Bitte prüfen, ob wir das vor dem Wochenendtermin beheben können.',
    },
    {
      id: 'msg-3',
      requestId: 'request-showroom-power',
      author: 'PixelRing Manager',
      sentAt: '2026-04-28 09:40',
      body: 'Die Messung ist abgeschlossen. Wir empfehlen den Austausch des Netzteils.',
    },
    {
      id: 'msg-4',
      requestId: 'request-showroom-power',
      author: 'Customer',
      sentAt: '2026-04-28 10:05',
      body: 'Bitte Ersatzteilfreigabe vorbereiten und Terminoptionen senden.',
    },
    {
      id: 'msg-5',
      requestId: 'request-showroom-power',
      author: 'PixelRing Manager',
      sentAt: '2026-04-28 10:36',
      body: 'Die Freigabe ist als Vorschau hinterlegt. Nach Ihrer Bestätigung reservieren wir das Fenster am 30.04. zwischen 09:00 und 11:00.',
    },
    {
      id: 'msg-6',
      requestId: 'request-window-refresh',
      author: 'PixelRing Manager',
      sentAt: '2026-04-09 16:20',
      body: 'Die Folierung wurde erneuert. Der Foto-Report und die Abnahmevorschau sind im Portal sichtbar.',
    },
    {
      id: 'msg-7',
      requestId: 'request-window-refresh',
      author: 'Customer',
      sentAt: '2026-04-09 17:04',
      body: 'Danke, die Flächen sehen sauber aus. Bitte den Bericht im Archiv belassen.',
    },
    {
      id: 'msg-8',
      requestId: 'request-hub-label',
      author: 'PixelRing AI',
      sentAt: '2026-04-26 14:16',
      body: 'Ich habe die beschädigte Torbeschriftung als Betriebskennzeichnung erkannt und die vorhandenen Objektinformationen zugeordnet.',
    },
    {
      id: 'msg-9',
      requestId: 'request-hub-label',
      author: 'PixelRing Manager',
      sentAt: '2026-04-28 11:12',
      body: 'Wir prüfen, ob das Label aus dem vorhandenen Datensatz nachproduziert werden kann.',
    },
    {
      id: 'msg-10',
      requestId: 'request-hub-label',
      author: 'PixelRing Manager',
      sentAt: '2026-04-28 12:05',
      body: 'Für die Druckfreigabe fehlt noch ein Foto der beschädigten rechten Kante aus gerader Perspektive.',
    },
    {
      id: 'msg-11',
      requestId: 'request-light-warranty',
      author: 'PixelRing Manager',
      sentAt: '2026-03-28 13:30',
      body: 'Das Lichtmodul wurde innerhalb der Garantie getauscht. Garantiebeleg und Kurzreport bleiben als Vorschau verfügbar.',
    },
  ],
  requestTimeline: [
    {
      id: 'timeline-power-1',
      requestId: 'request-showroom-power',
      state: 'done',
      title: 'Anfrage angenommen',
      description: 'Demo-Zugang und Objektbezug wurden bestätigt.',
      occurredAt: '2026-04-22 08:18',
    },
    {
      id: 'timeline-power-2',
      requestId: 'request-showroom-power',
      state: 'done',
      title: 'Technische Diagnose',
      description: 'Messwerte deuten auf ein instabiles Netzteil im Außenleuchtschild hin.',
      occurredAt: '2026-04-28 09:20',
    },
    {
      id: 'timeline-power-3',
      requestId: 'request-showroom-power',
      state: 'active',
      title: 'Kundenfreigabe',
      description: 'Kostenschätzung und Besuchsfenster warten auf Bestätigung.',
      occurredAt: '2026-04-28 10:36',
    },
    {
      id: 'timeline-power-4',
      requestId: 'request-showroom-power',
      state: 'upcoming',
      title: 'Technikerbesuch',
      description: 'Nach Freigabe wird das Ersatzteil reserviert und der Einsatz bestätigt.',
      occurredAt: 'Nach Freigabe',
    },
    {
      id: 'timeline-window-1',
      requestId: 'request-window-refresh',
      state: 'done',
      title: 'Auftrag erfasst',
      description: 'Schaufensterflächen und Motivdaten wurden dem Showroom zugeordnet.',
      occurredAt: '2026-04-04 10:10',
    },
    {
      id: 'timeline-window-2',
      requestId: 'request-window-refresh',
      state: 'done',
      title: 'Ausführung abgeschlossen',
      description: 'Folien wurden ersetzt und Glasflächen gereinigt.',
      occurredAt: '2026-04-09 15:40',
    },
    {
      id: 'timeline-window-3',
      requestId: 'request-window-refresh',
      state: 'done',
      title: 'Report bereit',
      description: 'Foto-Report und Abnahmevorschau liegen als Portalvorschau vor.',
      occurredAt: '2026-04-09 16:20',
    },
    {
      id: 'timeline-label-1',
      requestId: 'request-hub-label',
      state: 'done',
      title: 'Anfrage klassifiziert',
      description: 'Tor B wurde als betroffener Servicepunkt erkannt.',
      occurredAt: '2026-04-26 14:16',
    },
    {
      id: 'timeline-label-2',
      requestId: 'request-hub-label',
      state: 'active',
      title: 'Materialprüfung',
      description: 'PixelRing prüft Vorlage, Materialbestand und notwendige Maße.',
      occurredAt: '2026-04-28 11:12',
    },
    {
      id: 'timeline-label-3',
      requestId: 'request-hub-label',
      state: 'upcoming',
      title: 'Nachproduktion',
      description: 'Nach Fotoergänzung wird die Druckfreigabe vorbereitet.',
      occurredAt: 'Nach Foto',
    },
    {
      id: 'timeline-warranty-1',
      requestId: 'request-light-warranty',
      state: 'done',
      title: 'Garantiefall geprüft',
      description: 'Das Außenlichtmodul lag innerhalb des dokumentierten Garantiezeitraums.',
      occurredAt: '2026-03-21 09:30',
    },
    {
      id: 'timeline-warranty-2',
      requestId: 'request-light-warranty',
      state: 'done',
      title: 'Modul getauscht',
      description: 'Ersatzmodul wurde montiert und geprüft.',
      occurredAt: '2026-03-28 12:20',
    },
    {
      id: 'timeline-warranty-3',
      requestId: 'request-light-warranty',
      state: 'done',
      title: 'Garantiebeleg archiviert',
      description: 'Kundenansicht zeigt nur die freigegebene Vorschau.',
      occurredAt: '2026-03-28 13:30',
    },
  ],
  customerAttachments: [
    {
      id: 'att-power-night-photo',
      requestId: 'request-showroom-power',
      filename: 'showroom-sign-night-issue.jpg',
      fileType: 'JPG photo',
      uploadedAt: '2026-04-22',
      status: 'reviewed',
    },
    {
      id: 'att-power-flicker-video',
      requestId: 'request-showroom-power',
      filename: 'letter-flicker-short.mp4',
      fileType: 'MP4 video',
      uploadedAt: '2026-04-22',
      status: 'reviewed',
    },
    {
      id: 'att-window-artwork',
      requestId: 'request-window-refresh',
      filename: 'showroom-window-approved-artwork.pdf',
      fileType: 'PDF artwork',
      uploadedAt: '2026-04-04',
      status: 'reviewed',
    },
    {
      id: 'att-label-front',
      requestId: 'request-hub-label',
      filename: 'tor-b-label-front.jpg',
      fileType: 'JPG photo',
      uploadedAt: '2026-04-26',
      status: 'needs_more_context',
    },
    {
      id: 'att-warranty-module',
      requestId: 'request-light-warranty',
      filename: 'light-module-defect-before.jpg',
      fileType: 'JPG photo',
      uploadedAt: '2026-03-21',
      status: 'reviewed',
    },
  ],
  documents: [
    {
      id: 'doc-window-report',
      type: 'REPORT',
      title: 'Foto-Report Schaufensterfolierung',
      relatedTo: 'PR-DEMO-4730',
      requestId: 'request-window-refresh',
      issuedAt: '2026-04-09',
      status: 'available',
      description: 'Vorher/Nachher-Auswahl der erneuerten Glasflächen.',
    },
    {
      id: 'doc-window-acceptance',
      type: 'DOCUMENT',
      title: 'Abnahmevorschau Schaufenster',
      relatedTo: 'PR-DEMO-4730',
      requestId: 'request-window-refresh',
      issuedAt: '2026-04-09',
      status: 'available',
      description: 'Kundenfreigegebene Vorschau ohne interne Arbeitsnotizen.',
    },
    {
      id: 'doc-power-offer',
      type: 'OFFER',
      title: 'Freigabe Netzteiltausch',
      relatedTo: 'PR-DEMO-4821',
      requestId: 'request-showroom-power',
      issuedAt: '2026-04-28',
      status: 'planned',
      description: 'Kostenschätzung und Leistungsumfang als Vorschau, noch ohne Download.',
    },
    {
      id: 'doc-power-diagnostic',
      type: 'REPORT',
      title: 'Diagnosevorschau Außenleuchtschild',
      relatedTo: 'PR-DEMO-4821',
      requestId: 'request-showroom-power',
      issuedAt: '2026-04-28',
      status: 'available',
      description: 'Kundenfähige Zusammenfassung der Messwerte und Empfehlung.',
    },
    {
      id: 'doc-power-warranty-preview',
      type: 'WARRANTY',
      title: 'Garantie nach Netzteiltausch',
      relatedTo: 'PR-DEMO-4821',
      requestId: 'request-showroom-power',
      issuedAt: 'Nach Ausführung',
      status: 'locked',
      description: 'Wird erst nach abgeschlossenem Einsatz verfügbar.',
    },
    {
      id: 'doc-label-template',
      type: 'DOCUMENT',
      title: 'Druckvorlage Tor B',
      relatedTo: 'PR-DEMO-4894',
      requestId: 'request-hub-label',
      issuedAt: '2026-04-28',
      status: 'planned',
      description: 'Vorlage wird nach fehlendem Detailfoto bestätigt.',
    },
    {
      id: 'doc-label-report-preview',
      type: 'REPORT',
      title: 'Montage-Report Torbeschriftung',
      relatedTo: 'PR-DEMO-4894',
      requestId: 'request-hub-label',
      issuedAt: 'Nach Montage',
      status: 'locked',
      description: 'Report-Vorschau bleibt bis zur Ausführung gesperrt.',
    },
    {
      id: 'doc-light-warranty',
      type: 'WARRANTY',
      title: 'Garantiebeleg Lichtmodul',
      relatedTo: 'PR-DEMO-4612',
      requestId: 'request-light-warranty',
      issuedAt: '2026-03-28',
      status: 'available',
      description: 'Garantienachweis für das ersetzte Außenlichtmodul.',
    },
    {
      id: 'doc-light-report',
      type: 'REPORT',
      title: 'Kurzreport Lichtmodul',
      relatedTo: 'PR-DEMO-4612',
      requestId: 'request-light-warranty',
      issuedAt: '2026-03-28',
      status: 'available',
      description: 'Vorher/Nachher-Status und Funktionsprüfung.',
    },
    {
      id: 'doc-invoice-preview',
      type: 'INVOICE',
      title: 'Rechnungsbereich Vorschau',
      relatedTo: 'Pixel Ring GmbH',
      issuedAt: '2026-04-28',
      status: 'locked',
      description: 'Billing bleibt in Stage 2 bewusst gesperrt.',
    },
  ],
  requiredActions: [
    {
      id: 'action-power-approve',
      requestId: 'request-showroom-power',
      type: 'APPROVE_ESTIMATE',
      status: 'preview_only',
      description: 'Freigabe der Kostenschätzung für Netzteil, Technikerarbeit und Dichtigkeitsprüfung.',
      dueLabel: 'Demo-Aktion · keine Mutation',
    },
    {
      id: 'action-power-window',
      requestId: 'request-showroom-power',
      type: 'CONFIRM_VISIT_WINDOW',
      status: 'preview_only',
      description: 'Bevorzugtes Besuchsfenster: 30.04.2026 zwischen 09:00 und 11:00.',
      dueLabel: 'Nach Freigabe bestätigen',
    },
    {
      id: 'action-label-photo',
      requestId: 'request-hub-label',
      type: 'UPLOAD_MISSING_PHOTO',
      status: 'preview_only',
      description: 'Benötigt wird ein gerades Detailfoto der rechten beschädigten Kante an Tor B.',
      dueLabel: 'Vor Druckfreigabe',
    },
  ],
};

export function getPortalDemoEmail(): string {
  return (process.env.PORTAL_DEMO_EMAIL || PORTAL_DEMO_EMAIL_DEFAULT).trim().toLowerCase();
}

export function isPortalDemoEnabled(): boolean {
  return process.env.NODE_ENV !== 'production' && process.env.PORTAL_DEMO_ENABLED === 'true';
}

export function getPortalDemoRequestDetail(publicRequestNumber: string) {
  let normalizedRequestNumber = publicRequestNumber.trim().toUpperCase();

  try {
    normalizedRequestNumber = decodeURIComponent(publicRequestNumber).trim().toUpperCase();
  } catch {
    normalizedRequestNumber = '';
  }

  const request = portalDemoOrganization.requests.find(
    (item) => item.publicRequestNumber === normalizedRequestNumber
  );

  if (!request) {
    return null;
  }

  const portalObject = portalDemoOrganization.objects.find((item) => item.id === request.objectId);

  if (!portalObject) {
    return null;
  }

  return {
    organization: portalDemoOrganization,
    request,
    object: portalObject,
    assets: portalDemoOrganization.assets.filter((asset) => asset.objectId === portalObject.id),
    messages: portalDemoOrganization.messages.filter((message) => message.requestId === request.id),
    timeline: portalDemoOrganization.requestTimeline.filter((item) => item.requestId === request.id),
    customerAttachments: portalDemoOrganization.customerAttachments.filter(
      (attachment) => attachment.requestId === request.id
    ),
    documents: portalDemoOrganization.documents.filter((document) => document.requestId === request.id),
    requiredActions: portalDemoOrganization.requiredActions.filter((action) => action.requestId === request.id),
  };
}
